name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurando máquina GO
        uses: actions/setup-go@v2
        with: 
          go-version: 1.15

      - name: Run Teste GO
        run: go test

      - name: Run programa GO
        run: go run math.go

      - name: Configurando Docker QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configurando Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          push: false
          tags: felipemarchant/fc2.0-ci-go:latest