name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: 1.15
      - run: go test
      - run: go run math.go

      - name: Configurando Docker QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configurando Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login no DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: felipemarchant/fc2.0-ci-go:latest